upstream fastapi {
    server fastapi:8000;
}

server {
    server_name localhost _;

    listen 80;

    # 추후 certbot ssl 인증서 갱신 시 필요
    location /.well-known/acme-challenge/ {
       root /var/www/certbot;
    }

    location /api/ {
        proxy_pass http://fastapi;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        # SSE 스트리밍을 위한 타임아웃 설정
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location / {
        root /vol/web/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
